language: ruby
bundler_args: --without development --path vendor/bundle --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle
before_install:
  - gem update --system
install:
  - gem install bundler
  - bundle install
script: bundle exec rspec

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
